/* eslint-disable import/prefer-default-export */

export const REQUEST_START = "REQUEST_START";

// Authentication
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

// Player
export const INIT_PLAYER_START = 'INIT_PLAYER_START'
export const INIT_PLAYER_SUCCESS = 'INIT_PLAYER_SUCCESS'
export const INIT_PLAYER_FAILURE = 'INIT_PLAYER_FAILURE'

// Player Movement
export const MOVE_PLAYER_START = 'MOVE_PLAYER_START';
export const MOVE_PLAYER_SUCCESS = 'MOVE_PLAYER';
export const MOVE_PLAYER_FAILURE = 'MOVE_PLAYER_FAILURE';

// Player Challenges
export const COMPLETE_CHALLENGE_START = 'COMPLETE_CHALLENGE_START';
export const COMPLETE_CHALLENGE_SUCCESS = 'COMPLETE_CHALLENGE_SUCCESS';
export const COMPLETE_CHALLENGE_FAILURE = 'COMPLETE_CHALLENGE_FAILURE';
export const FAIL_CHALLENGE = 'FAIL_CHALLENGE';

// Dialogue
export const DISPLAY_QUESTION = "DISPLAY_QUESTION";
export const DISPLAY_CHOICE = "DISPLAY_CHOICE";
export const DISPLAY_FAILURE = "DISPLAY_FAILURE";
export const NEXT_QUESTION = "NEXT_QUESTION";

// Finish Game
export const COMPLETE_GAME = "COMPLETE_GAME";

// Rooms
export const GET_ROOMS_START = 'GET_ROOMS_START';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_FAILURE = 'GET_ROOMS_FAILURE';
