/* eslint-disable import/prefer-default-export */

export const REQUEST_START = "REQUEST_START";

// Authentication
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

// Player
export const INIT_PLAYER_START = 'INIT_PLAYER_START'
export const INIT_PLAYER_SUCCESS = 'INIT_PLAYER_SUCCESS'
export const INIT_PLAYER_FAILURE = 'INIT_PLAYER_FAILURE'

// Player Movement
export const MOVE_PLAYER_START = 'MOVE_PLAYER_START';
export const MOVE_PLAYER_UP = 'MOVE_PLAYER_UP';
export const MOVE_PLAYER_DOWN = 'MOVE_PLAYER_DOWN';
export const MOVE_PLAYER_LEFT = 'MOVE_PLAYER_LEFT';
export const MOVE_PLAYER_RIGHT = 'MOVE_PLAYER_RIGHT';
export const MOVE_PLAYER_FAILURE = 'MOVE_PLAYER_FAILURE';

// Player Challenge Complete
export const COMPLETE_CHALLENGE_START = 'COMPLETE_CHALLENGE_START';
export const COMPLETE_CHALLENGE_SUCCESS = 'COMPLETE_CHALLENGE_SUCCESS';
export const COMPLETE_CHALLENGE_FAILURE = 'COMPLETE_CHALLENGE_FAILURE';

// Rooms
export const GET_ROOMS_START = 'GET_ROOMS_START';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_FAILURE = 'GET_ROOMS_FAILURE';
